package com.atlaspay.auth.domain.exception;

import com.atlaspay.shared.exception.ErrorCode;

public enum AuthErrorCode implements ErrorCode {
    AUTH_ACCOUNT_NOT_FOUND, AUTH_ACCOUNT_ALREADY_EXISTS, ACCOUNT_NOT_ACTIVE,
    ACCOUNT_SUSPENDED, ACCOUNT_LOCKED, INVALID_CREDENTIAL, INVALID_VERIFICATION_CODE,
    VERIFICATION_EXPIRED, MAX_ATTEMPTS_EXCEEDED, INVALID_TOTP_CODE, TOTP_ALREADY_ENABLED,
    TOTP_NOT_ENABLED, INVALID_PRE_AUTH_TOKEN, PRE_AUTH_TOKEN_EXPIRED, SESSION_NOT_FOUND,
    SESSION_ALREADY_REVOKED, INVALID_REFRESH_TOKEN, REFRESH_TOKEN_EXPIRED, TOKEN_REUSE_DETECTED, ACCOUNT_ALREADY_SUSPENDED, INVALID_REQUEST;
}
