package com.atlaspay.identity.domain.exception;

import com.atlaspay.shared.exception.ErrorCode;

/**
 * All error codes specific to the Identity bounded context.
 */
public enum IdentityErrorCode implements ErrorCode {
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_EXISTS,
    USER_LOCKED,
    MERCHANT_SUSPENDED,
    MERCHANT_EMAIL_ALREADY_EXISTS,
    EMAIL_ALREADY_VERIFIED,
    EMAIL_CODE_NOT_FOUND,
    EMAIL_CODE_INVALID_OR_EXPIRED,
    EMAIL_VERIFICATION_REQUIRED,
    RC_NUMBER_REQUIRED_FOR_REGISTERED_BUSINESS,
    COMPLIANCE_STEP_OUT_OF_ORDER,
    COMPLIANCE_NOT_ALL_STEPS_COMPLETE,
    COMPLIANCE_NOT_SUBMITTED,
    KYC_VERIFICATION_FAILED,
    BANK_ACCOUNT_NOT_FOUND,
    ACCOUNT_RESOLUTION_PROVIDER_UNAVAILABLE,
    API_KEY_NOT_FOUND,
    API_KEY_ALREADY_REVOKED,
    LIVE_KEYS_REQUIRE_COMPLIANCE_APPROVED,
    MERCHANT_NOT_FOUND
}
