rootProject.name = 'atlaspay'

include 'atlaspay-shared-kernel'
include 'atlaspay-identity'
include 'atlaspay-accounts'
include 'atlaspay-ledger'
include 'atlaspay-transfers'
include 'atlaspay-charges'
include 'atlaspay-subscriptions'
include 'atlaspay-escrow'
include 'atlaspay-settlement'
include 'atlaspay-transaction-splits'
include 'atlaspay-transactions-query'
include 'atlaspay-notifications'
include 'atlaspay-rate-limiter'
include 'atlaspay-eventbus'
include 'atlaspay-simulator'
include 'atlaspay-app'