dependencies {
    implementation project(':atlaspay-shared-kernel')

    // Spring context for @Service and @Transactional
    implementation 'org.springframework.boot:spring-boot-starter'
    // Spring Data JPA for persistence annotations and transaction management
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}
