package com.atlaspay.ledger.application.usecase;

import com.atlaspay.ledger.application.command.PostLedgerTransactionCommand;
import com.atlaspay.ledger.domain.exception.LedgerErrorCode;
import com.atlaspay.ledger.domain.model.LedgerEntry;
import com.atlaspay.ledger.domain.model.LedgerTransaction;
import com.atlaspay.ledger.domain.model.TransactionReference;
import com.atlaspay.ledger.domain.repository.LedgerEntryRepository;
import com.atlaspay.ledger.domain.repository.LedgerTransactionRepository;
import com.atlaspay.shared.exception.ConflictException;
import com.atlaspay.shared.money.Money;
import com.atlaspay.shared.usecase.BaseUseCase;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.ZonedDateTime;
import java.util.List;

@Service
public class PostLedgerTransactionUseCase extends BaseUseCase<PostLedgerTransactionCommand, Void> {

    private final LedgerTransactionRepository ledgerTransactionRepository;
    private final LedgerEntryRepository ledgerEntryRepository;

    public PostLedgerTransactionUseCase(LedgerTransactionRepository ledgerTransactionRepository, LedgerEntryRepository ledgerEntryRepository) {
        this.ledgerTransactionRepository = ledgerTransactionRepository;
        this.ledgerEntryRepository = ledgerEntryRepository;
    }

    @Override
    @Transactional
    public Void execute(PostLedgerTransactionCommand command) {
        // Idempotency constraint using uniqueness check
        if (ledgerTransactionRepository.existsByReference(command.transactionId(), command.sourceSystem())) {
            throw new ConflictException(LedgerErrorCode.TRANSACTION_ALREADY_POSTED, "Transaction already posted");
        }

        TransactionReference reference = new TransactionReference(command.transactionId(), command.sourceSystem());

        // Map entries
        List<LedgerEntry> entries = command.entries().stream().map(entry -> 
            new LedgerEntry(
                ledgerEntryRepository.nextIdentity(), // ID generated by DB/Repository
                entry.accountId(),
                Money.of(entry.amount(), entry.currency()),
                entry.type(),
                reference,
                entry.description(),
                ZonedDateTime.now()
            )
        ).toList();

        // Instantiate Aggregate Root which enforces Double-Entry balancing constraints
        LedgerTransaction transaction = new LedgerTransaction(ledgerTransactionRepository.nextIdentity(), reference, entries, ZonedDateTime.now());

        ledgerTransactionRepository.save(transaction);

        return null;
    }
}
